name: Deploy to ZAP Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to ZAP via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ${{ secrets.ZAP HOST }}
          username: ${{ secrets.ZAP USER }}
          password: ${{ secrets.ZAP PASSWORD }}
          server-dir: /gta5-fivem/server-data/resources
          local-dir: ./resources
          protocol: sftp